export const test1 = require('./test.json')
export const test2 = require('./test2.json')
export const test3 = require('./test3.json')
export const test4 = require('./test4.json')
export const test5 = require('./test5.json')
